on:
  release:
    types:
      - published
name: release
jobs:
  release:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y curl jq
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Publish release
        run: ./.github/release.sh ${{ secrets.CRATES_IO_TOKEN }}
